# Generated by Django 6.0.7 on 2026-07-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'پروفایل کاربر'},
        ),
    ]
