# Generated by Django 6.0.7 on 2026-07-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_image_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_approved',
            new_name='is_active',
        ),
    ]
