# Generated by Django 6.0.7 on 2026-07-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_comment_product_alter_comment_reply_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'محصول'},
        ),
    ]
